### ISSUE TITLE
about pre_model

### ISSUE THREAD

**Issue by tongchangD** [bwconrad/decoder-denoising#2]
can you share your pretrained models

**Comment by bwconrad** [comment]
I've not done the full pretraining on imagenet so I unfortunately do not have any weights to share. I've only done small experiments on some personal datasets to make sure the code is working correctly.

**Comment by tongchangD** [comment]
> I've not done the full pretraining on imagenet so I unfortunately do not have any weights to share. I've only done small experiments on some personal datasets to make sure the code is working correctly.

thanks
