### ISSUE TITLE
these parameters are not present

### ISSUE THREAD

**Issue by yao-yu1999** [bwconrad/decoder-denoising#6]
When I train, it shows that these parameters are not present
![image](https://github.com/bwconrad/decoder-denoising/assets/81399827/66a802b4-5225-4213-9a0e-5f30352b02e4)

**Comment by bwconrad** [comment]
What version of pytorch lightning are you using? In more recent versions, the `--gpus 1` argument has been replaced with `--accelerator gpu --devices 1`. If you are using version `1.6.4` as found in `requirements.txt` then this error will not happen.

**Comment by yao-yu1999** [comment]
> What version of pytorch lightning are you using? In more recent versions, the `--gpus 1` argument has been replaced with `--accelerator gpu --devices 1`. If you are using version `1.6.4` as found in `requirements.txt` then this error will not happen.

ok, i'll try. Thank you
